crm/crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from questionnaire_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^meeting_room/', include('meeting_room_app.urls')),
    url(r'^questionnaire/', include('questionnaire_app.urls'))
]

crm/meeting_room_app/models.py
from django.db import models


class User(models.Model):
    """ 用户表
    普通字段:
        id, username, password
    """

    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=32, verbose_name='用户名')
    password = models.CharField(max_length=32, verbose_name='密码')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = '用户表'


class MeetingRoom(models.Model):
    """ 会议室表
    普通字段:
        id, title
    """

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32, verbose_name='会议室名称')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '会议室表'


class Order(models.Model):
    """ 会议室预定表
    普通字段:
        id, schedule_date
    关联字段:
        period, user
    """

    id = models.AutoField(primary_key=True)

    period_list = [
        (1, "8:00~9:00"),
        (2, "9:00~10:00"),
        (3, "10:00~11:00"),
        (4, "11:00~12:00"),
        (5, "12:00~13:00"),
        (6, "13:00~14:00"),
        (7, "14:00~15:00"),
        (8, "15:00~16:00"),
        (9, "16:00~17:00"),
        (10, "17:00~18:00"),
        (11, "18:00~19:00"),
        (12, "19:00~20:00"),
        (13, "20:00~21:00")
    ]
    period = models.IntegerField(choices=period_list, verbose_name='时间段')

    schedule_date = models.DateField(verbose_name='预定时间')
    room = models.ForeignKey(to='MeetingRoom', to_field='id')
    user = models.ForeignKey(to='User', to_field='id')

    def __str__(self):
        return f'{self.schedule_date}:{self.period}：{self.id}'

    class Meta:
        verbose_name_plural = '会议室预定表'
        unique_together = (("room", "period", "schedule_date"),)

crm/questionnaire_app/models.py
from django.db import models


class Department(models.Model):
    """ 部门表
    普通字段:
        id, dep_name
    """

    id = models.AutoField(primary_key=True)
    department_name = models.CharField(max_length=16, blank=True, verbose_name='部门名称')

    def __str__(self):
        return self.department_name

    class Meta:
        verbose_name_plural = '部门表'


class Employee(models.Model):
    """ 用户信息表
    普通字段:
        id, username, password
    关联字段:
        department(多对一, to=Department.id)
    """

    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=32, verbose_name='用户名')
    password = models.CharField(max_length=32, verbose_name='密码')

    department = models.ForeignKey(to='Department', to_field='id', verbose_name='部门')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = '用户表'


class Admin(models.Model):
    """ 管理员表
    普通字段:
        username, password
    """

    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=32, verbose_name='用户名')
    password = models.CharField(max_length=32, verbose_name='密码')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = '管理员表'


class Questionnaire(models.Model):
    """ 问卷表
    普通字段:
        id, title, description
    关联字段:
        department(一对一, to=BanJi.id)
    """

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32, verbose_name='问卷标题')
    description = models.CharField(max_length=512, verbose_name='问卷描述')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    admin = models.ForeignKey(to='Admin', to_field='id', verbose_name='创建人')
    department = models.ForeignKey(to='Department', to_field='id', verbose_name='接受调查的部门')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '问卷表'


class Question(models.Model):
    """ 问题表
    普通字段:
        id, question_type, content
    关联字段:
        questionnaire(多对一, to=Questionnaire.id)
    """

    id = models.AutoField(primary_key=True)
    question_type_choices = [
        (1, "单选"),
        (2, "多选"),
        (3, "打分"),
        (4, "建议"),
    ]
    question_type = models.IntegerField(choices=question_type_choices, verbose_name='问题类型')
    content = models.CharField(max_length=256, verbose_name='问题内容')

    questionnaire = models.ForeignKey(to='Questionnaire', to_field='id', verbose_name='所属问卷')

    def __str__(self):
        return self.content

    class Meta:
        verbose_name_plural = '问题表'


class Choice(models.Model):
    """ 问题选项表
    普通字段:
        id, 标题, 选项值
    关联字段:
        question(多对一， to=Question.id)
    """

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32, verbose_name='选项标题')
    score = models.IntegerField(verbose_name='选项分数')
    # choice_value = models.CharField(max_length=128, verbose_name='选项值')  # 存放json字符串

    question = models.ForeignKey(to='Question', to_field='id', verbose_name='所属问题')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '问题选项表'


class Answer(models.Model):
    """ 答案表
    普通字段:
        id, content(json)
    关联字段:
        employee(多对一, to=User.id)
        question(多对一, to=Question.id)
    """

    id = models.AutoField(primary_key=True)

    choice = models.ForeignKey(to="Choice", null=True, blank=True)
    val = models.IntegerField(null=True, blank=True)
    content = models.CharField(max_length=255, null=True, blank=True)

    employee = models.ForeignKey(to='Employee', to_field='id', verbose_name='回答员工')
    question = models.ForeignKey(to='Question', to_field='id', verbose_name='对应问题')

    def __str__(self):
        return self.content

    class Meta:
        unique_together = (('employee', 'question'), )
        verbose_name_plural = '答案表'

crm/templates/add_questionnaire.html
{% extends 'list_questionnaire.html' %}

{% block content %}
    <h2>新增问卷</h2>
    <hr>
    <div class="row">
    {% csrf_token %}
        <div class="form-group">
            <label class="control-label" for="id_title">问卷标题</label>
            {{ form.title }}
            <span id="title" class="help-block"></span>
        </div>
        <div class="form-group">
            <label class="control-label" for="id_description">问卷描述</label>
            {{ form.description }}
            <span id="description" class="help-block"></span>
        </div>
        <div class="form-group">
            <label class="control-label" for="id_department">参与问卷部门</label>
            <select name="select" id="id_department" class="form-control" multiple>
                {% for department in departments %}
                    <option value="{{ department.id }}">{{ department.department_name }}</option>
                {% endfor %}
            </select>
            <span id="department" class="help-block"></span>
        </div>
    <div class="col-md-12 text-center">
            <button id="add_questionnaire" class="btn btn-success">添加</button>
    </div>
    </div>
{% endblock %}

crm/templates/base.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM</title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/htmleaf-demo.css">
    <link rel="stylesheet" type="text/css" href="/static/css/nav.css">
    <link rel="stylesheet" type="text/css" href="/static/fonts/iconfont.css">
</head>
<body>

<div class="nav">
    <div class="nav-top">
        <div id="mini" style="border-bottom:1px solid rgba(255,255,255,.1)"><img src="/static/img/mini.png">&nbsp;&nbsp;CRM系统
        </div>
    </div>
    <ul>
        <li class="nav-item">
            <a href="javascript:;"><i class="my-icon nav-icon icon_1"></i><span>导航</span><i
                    class="my-icon nav-more"></i></a>
            <ul>
                <li><a href="/home/"><span>回到网站主页</span></a></li>
                <li><a href=""><span>个人主页</span></a></li>
                <li><a href="javascript:;"><span>修改密码</span></a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="javascript:;"><i class="my-icon nav-icon icon_2"></i><span>问卷管理</span><i
                    class="my-icon nav-more"></i></a>
            <ul>
                <li><a href="/add_questionnaire/"><span>新增问卷调查</span></a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="javascript:;"><i class="my-icon nav-icon icon_3"></i><span>分类管理</span><i
                    class="my-icon nav-more"></i></a>
            <ul>
                <li><a href=""><span>分类列表</span></a></li>
                <li><a href=""><span>添加分类</span></a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="javascript:;"><i class="my-icon nav-icon icon_3"></i><span>标签管理</span><i
                    class="my-icon nav-more"></i></a>
            <ul>
                <li><a href="javascript:;"><span>订单列表</span></a></li>
                <li><a href="javascript:;"><span>打个酱油</span></a></li>
                <li><a href="javascript:;"><span>也打酱油</span></a></li>
            </ul>
        </li>
    </ul>
</div>
<div class="content">
    <div class="col-md-10 col-md-offset-2">
        {% block content %}

        {% endblock %}
    </div>

</div>

<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="http://cdn.bootcss.com/jquery/1.11.0/jquery.min.js" type="text/javascript"></script>
<script>window.jQuery || document.write('<script src="js/jquery-1.11.0.min.js"><\/script>')</script>
<script type="text/javascript" src="/static/js/nav.js"></script>
<script type="text/javascript" src="/static/js/list_orders.js"></script>
</body>
</html>

crm/templates/list_orders.html
{% extends 'base.html' %}

{% block content %}
    <h1>会议室预定</h1>
    <hr>
    <table class="table table-hover table-bordered">
        <thead>
        <tr>
            <th>会议室</th>
            <th>8:00</th>
            <th>9:00</th>
            <th>10:00</th>
            <th>11:00</th>
            <th>12:00</th>
            <th>13:00</th>
            <th>14:00</th>
            <th>15:00</th>
            <th>16:00</th>
            <th>17:00</th>
            <th>18:00</th>
            <th>19:00</th>
            <th>20:00</th>
        </tr>
        </thead>
        <tbody>
            {% for room in rooms %}
                <tr>
                    <td>{{ room.title }}</td>
                    {% for period in period_list %}
                        {% for item in order_list %}
                            {% if room == item.1 %}
                                {% if item.0.period == period.0 %}
                                    <td>{{ item.0.user.username }}</td>
                                {% endif %}
                             {% endif %}
                        {% endfor %}
                        <td></td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>

    </table>
{% endblock %}

crm/templates/list_questionnaire.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM</title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/htmleaf-demo.css">
    <link rel="stylesheet" type="text/css" href="/static/css/nav.css">
    <link rel="stylesheet" type="text/css" href="/static/css/manage_questionnaire.css">
    <link rel="stylesheet" type="text/css" href="/static/fonts/iconfont.css">
</head>
<body>

<div class="nav">
    <div class="nav-top">
        <div id="mini" style="border-bottom:1px solid rgba(255,255,255,.1)"><img src="/static/img/mini.png">&nbsp;&nbsp;CRM系统
        </div>
    </div>
    <ul>
        <li class="nav-item">
            <a href="javascript:;"><i class="my-icon nav-icon icon_1"></i><span>导航</span><i
                    class="my-icon nav-more"></i></a>
            <ul>
                <li><a href="/home/"><span>回到网站主页</span></a></li>
                <li><a href=""><span>个人主页</span></a></li>
                <li><a href="javascript:;"><span>修改密码</span></a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="javascript:;"><i class="my-icon nav-icon icon_2"></i><span>问卷管理</span><i
                    class="my-icon nav-more"></i></a>
            <ul>
                <li><a href="/add_questionnaire/"><span>新增问卷调查</span></a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="javascript:;"><i class="my-icon nav-icon icon_3"></i><span>分类管理</span><i
                    class="my-icon nav-more"></i></a>
            <ul>
                <li><a href=""><span>分类列表</span></a></li>
                <li><a href=""><span>添加分类</span></a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="javascript:;"><i class="my-icon nav-icon icon_3"></i><span>标签管理</span><i
                    class="my-icon nav-more"></i></a>
            <ul>
                <li><a href="javascript:;"><span>订单列表</span></a></li>
                <li><a href="javascript:;"><span>打个酱油</span></a></li>
                <li><a href="javascript:;"><span>也打酱油</span></a></li>
            </ul>
        </li>
    </ul>
</div>
<div class="content">
    <div class="col-md-10 col-md-offset-2">
        {% block content %}
            <div class="row">
                <h2>问卷列表</h2>
                <hr>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>问卷调查名称</th>
                        <th>问卷调查部门</th>
                        <th>参与人数</th>
                        <th>查看评分</th>
                        <th>调查地址</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for questionnaire in questionnaires %}
                        <tr>
                            <td>{{ questionnaire.title }}</td>
                            <td>{{ questionnaire.department.department_name }}</td>
                            <td></td>
                            <td>
                                <a href="{% url 'show_score' department_id=questionnaire.department.id questionnaire_id=questionnaire.id %}">查看评分</a>
                            </td>
                            <td>
                                <a href=""></a>
                            </td>
                            <td>
                                <a href="">
                                    <button class="btn btn-danger">删除</button>
                                </a>
                                <a href="{% url 'manage_questionnaire' questionnaire_id=questionnaire.id %}">
                                    <button class="btn btn-warning">编辑</button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endblock %}
    </div>

</div>

<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="http://cdn.bootcss.com/jquery/1.11.0/jquery.min.js" type="text/javascript"></script>
<script>window.jQuery || document.write('<script src="js/jquery-1.11.0.min.js"><\/script>')</script>
<script type="text/javascript" src="/static/js/nav.js"></script>
<script src="/static/js/admin_home.js"></script>
<script src="/static/js/manage_questionnaire.js"></script>
<script src="/static/js/add_questionnaire.js"></script>
</body>
</html>

crm/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>员工调查问卷系统</title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/login.css">
</head>
<body>

<div class="container ">
    <div class="row my-style">
        <div class="col-md-4 col-md-offset-5">
            <p class="title">登陆后，接受爸爸的调查吧</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <!-- form 表单 -->
            <form class="form-horizontal" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username" class="col-sm-4 control-label text-justify">用户名</label>
                    <div class="col-sm-8">
                        {{ form.username }}
                        <span id="username" class="help-block my-display"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-sm-4 control-label text-justify">密码</label>
                    <div class="col-sm-8">
                        {{ form.password }}
                        <span id="password" class="help-block"></span>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> 下次自动登录
                            </label>
                        </div>
                    </div>
                </div>
            </form>
            <div class="col-md-8 col-md-offset-5">
                    <button class="btn btn-default"  id="login" style="font-weight: bold;color: #904">登陆</button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="http://static.geetest.com/static/tools/gt.js"></script>
<script src="/static/js/login.js"></script>
</body>
</html>

crm/templates/manage_questionnaire.html
{% extends 'list_questionnaire.html' %}

{% block content %}
    <h2>编辑问卷</h2>
    <input type="hidden" value="{% url 'manage_questionnaire' questionnaire_id=questionnaire_id %}">
    {% csrf_token %}
    <hr>
    <div class="row">
        <div class="col-md-12">
            <button id="add_question" class="btn pull-right btn-success">添加</button>

            <button id="submit_question" class="btn pull-right btn-primary">提交</button>
        </div>

        <div class="question_area" class="col-md-12">

            <ol>
                {% for question in question_list %}
                <li >
                    <div class="per_question" question_id="{{ question.question.id }}">
                       <span class="glyphicon glyphicon-remove pull-right delete_choice" aria-hidden="true"></span>
                        <div class="col-md-12">
                            <div class="col-md-1">
                                问题内容:&nbsp;
                            </div>
                            <div class="col-md-10">
                                {{ question.form.content }}
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="col-md-1">
                                问题类型:&nbsp;
                            </div>
                            <div class="col-md-3">
                               {{ question.form.question_type }}
                            </div>
                            <div class="col-md-1 {{ question.option_class }}">
                                <button class="btn btn-default add_option">+添加选项</button>
                            </div>
                            <ul class="choice_list list-unstyled">
                                {% for choice in question.options %}
                                    <li>
                                        <div choice_id="{{ choice.choice.id }}" class="per_choice">
                                            <div class="col-md-12">
                                                <div class="col-md-4">
                                                    <div class="col-md-3">
                                                        选项:
                                                    </div>
                                                     <div class="col-md-8">
                                                         {{ choice.form.title }}
                                                     </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="col-md-3">
                                                         分值:
                                                    </div>
                                                     <div class="col-md-8">
                                                         {{ choice.form.score }}
                                                     </div>
                                                </div>
                                                <div class="col-md-2 text-center">
                                                    <span class="glyphicon glyphicon-remove delete_choice" aria-hidden="true"></span>

                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>

                    </div>
                </li>
                {% endfor %}
            </ol>
        </div>
    </div>
{% endblock %}

crm/templates/questionnaire.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>问卷调查页面</title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style>
        ul  li{
            display: inline-block;
            margin-left: 20px;
        }
    </style>
</head>
<body>
<div class="container">
    <h2>你好，{{ request.session.username }}。请完成下面的问卷调查</h2>
    <div class="row">
        <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div>
                <p>{{ field.label }}{{ field.errors }}</p>
                {{ field }}
            </div>
        {% endfor %}
            <button type="submit" class="btn" id="submit_questionnire">提交</button>
        </form>
    </div>
</div>


<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>